### ISSUE TITLE
muscle gain based on fitness level equation

### ISSUE THREAD

**Issue by thinklikeadesigner** [thinklikeadesigner/FlexFactor#17]
<img width="1077" alt="Screenshot 2023-04-08 at 10 03 59 PM" src="https://user-images.githubusercontent.com/58955802/230751950-5dbe0672-03ce-4a0e-bf4f-719e5463c904.png">

found it!!

if we have the percentage we can gain per month of bodyweight, and the number of lbs of bodyweight, we can find how long it takes to get to that bodyweight

**Comment by thinklikeadesigner** [comment]
So the formula for how long it takes to reach x lbs of muscle is


$$Starting Bodyweight \times Rate of Muscle = \text{lbs per month}$$

$$\frac{\text{Goal lbs of Muscle}}{\text{lbs of Muscle per month}} = \text{Time to Goal}$$

so the variables we need are the users goal in terms of lbs of lean muscle, the user's fitness level, the users sex, and the users total bodyweight

**Comment by thinklikeadesigner** [comment]
So the formula for how long it takes to reach x lbs of muscle is


$$Starting Bodyweight \times Rate of Muscle = \text{lbs per month}$$

$$\frac{\text{Goal lbs of Muscle}}{\text{lbs of Muscle per month}} = \text{Time to Goal}$$

so the variables we need are the users goal in terms of lbs of lean muscle, the user's fitness level, the users sex, and the users total bodyweight

**Comment by mentalcaries** [comment]
I think I'll use an average value for each range, since it'll be hard to really say where the users fall in the range.
