### ISSUE TITLE
Create user friendly measurement inputs

### ISSUE THREAD

**Issue by mentalcaries** [thinklikeadesigner/FlexFactor#37]
As a user:
- I'd like to enter my height in a unit that I do not need to calculate: feet/inches (imperial) or cm? (metric)
_Does using metric units mean we will also have to give results in metric units?_

**Comment by thinklikeadesigner** [comment]
i think all inputs and outputs should be imperial, and any metric units should stay inside the function and if need be, converted back to imperial for the output

**Comment by mentalcaries** [comment]
Well I think in the case of the UI for now, just leave everything as imperial. 
Maybe once time allows, we can add a toggle for metric?

**Comment by thinklikeadesigner** [comment]
Yeah, we can do a metric toggle in v2. For right now tho it looks like you fixed the issue with a function and the height slider, correct? Can we close this issue? @mentalcaries
