### ISSUE TITLE
Create a store for reusable values

### ISSUE THREAD

**Issue by mentalcaries** [thinklikeadesigner/FlexFactor#38]
There will be multiple values entered by the user, and many values derived as a result.

We want to have these values globally accessible for all the calculators that require them.

**Comment by thinklikeadesigner** [comment]
Okay I can take this on. I'll find all the inputs and wire them up to a global store

**Comment by thinklikeadesigner** [comment]
I had this figured out this morning but there was a bug that completely blew up my mental model and I got confused. Still a WIP

**Comment by thinklikeadesigner** [comment]
working on this with #55

**Comment by thinklikeadesigner** [comment]
done
