### ISSUE TITLE
Disclaimer about accuracy

### ISSUE THREAD

**Issue by mentalcaries** [thinklikeadesigner/FlexFactor#39]
Should we include a disclaimer about this calculator being intended as a guide?

The research used was presented in a general sense and only takes into consideration the parameters we provide for modification.
Of course, there are many other factors that will affect bulking and p-ratio including and not limited to:
- diet and nutrition
- training regime and consistency
- genetics
- body type
- supplementation
- rest
- stress levels

**Comment by thinklikeadesigner** [comment]
Maybe we can put a note in the footer
